// constants/privileges.js
const PRIVILEGES = {
    TICKETS_TEMP: {
        ADD_PRODUCTOS: 'TICKETS_TEMP.ADD_PRODUCTOS',
        REMOVE_PRODUCTOS: 'TICKETS_TEMP.REMOVE_PRODUCTOS',
        MODIFY_CANTIDAD: 'TICKETS_TEMP.MODIFY_CANTIDAD',
        MODIFY_INGREDIENTES_UNCOOKED: 'TICKETS_TEMP.MODIFY_INGREDIENTES_UNCOOKED',
        MODIFY_INGREDIENTES_ALL: 'TICKETS_TEMP.MODIFY_INGREDIENTES_ALL',
        APPLY_DESCUENTO: 'TICKETS_TEMP.APPLY_DESCUENTO',
        SPLIT_CUENTA: 'TICKETS_TEMP.SPLIT_CUENTA',
        JOIN_MESAS: 'TICKETS_TEMP.JOIN_MESAS',
        MOVE_PRODUCTOS: 'TICKETS_TEMP.MOVE_PRODUCTOS',
        CONFIRMAR_PEDIDO: 'TICKETS_TEMP.CONFIRMAR_PEDIDO'
    },
    TICKETS: {
        VIEW: 'TICKETS.VIEW',
        REPRINT: 'TICKETS.REPRINT',
        MODIFY_METODO_PAGO: 'TICKETS.MODIFY_METODO_PAGO',
        CREATE_FACTURA_A: 'TICKETS.CREATE_FACTURA_A',
        VIEW_HISTORY: 'TICKETS.VIEW_HISTORY',
        REOPEN: 'TICKETS.REOPEN'
    },
    MESAS: {
        CREATE: 'MESAS.CREATE',
        READ: 'MESAS.READ',
        UPDATE: 'MESAS.UPDATE',
        DELETE: 'MESAS.DELETE'
    },
    CUENTAS: {
        CREATE: 'CUENTAS.CREATE',
        READ: 'CUENTAS.READ',
        UPDATE: 'CUENTAS.UPDATE',
        DELETE: 'CUENTAS.DELETE'
    },
    ROLES: {
        CREATE: 'ROLES.CREATE',
        READ: 'ROLES.READ',
        UPDATE: 'ROLES.UPDATE',
        DELETE: 'ROLES.DELETE'
    },
    SALONES: {
        CREATE: 'SALONES.CREATE',
        READ: 'SALONES.READ',
        UPDATE: 'SALONES.UPDATE',
        DELETE: 'SALONES.DELETE'
    },
    PRODUCTOS: {
        CREATE: 'PRODUCTOS.CREATE',
        READ: 'PRODUCTOS.READ',
        UPDATE: 'PRODUCTOS.UPDATE',
        DELETE: 'PRODUCTOS.DELETE'
    },
    INGREDIENTES: {
        CREATE: 'INGREDIENTES.CREATE',
        READ: 'INGREDIENTES.READ',
        UPDATE: 'INGREDIENTES.UPDATE',
        DELETE: 'INGREDIENTES.DELETE'
    },
    CLIENTES: {
        CREATE: 'CLIENTES.CREATE',
        READ: 'CLIENTES.READ',
        UPDATE: 'CLIENTES.UPDATE',
        DELETE: 'CLIENTES.DELETE'
    },
    METODOS_PAGO: {
        CREATE: 'METODOS_PAGO.CREATE',
        READ: 'METODOS_PAGO.READ',
        UPDATE: 'METODOS_PAGO.UPDATE',
        DELETE: 'METODOS_PAGO.DELETE'
    },
    COMERCIO: {
        CREATE: 'COMERCIO.CREATE',
        READ: 'COMERCIO.READ',
        UPDATE: 'COMERCIO.UPDATE',
        DELETE: 'COMERCIO.DELETE'
    },
    CATEGORIAS: {
        CREATE: 'CATEGORIAS.CREATE',
        READ: 'CATEGORIAS.READ',
        UPDATE: 'CATEGORIAS.UPDATE',
        DELETE: 'CATEGORIAS.DELETE'
    },
    SUBCATEGORIAS: {
        CREATE: 'SUBCATEGORIAS.CREATE',
        READ: 'SUBCATEGORIAS.READ',
        UPDATE: 'SUBCATEGORIAS.UPDATE',
        DELETE: 'SUBCATEGORIAS.DELETE'
    },
    ZONAS_IMPRESION: {
        CREATE: 'ZONAS_IMPRESION.CREATE',
        READ: 'ZONAS_IMPRESION.READ',
        UPDATE: 'ZONAS_IMPRESION.UPDATE',
        DELETE: 'ZONAS_IMPRESION.DELETE'
    },
    CAJAS: {
        CLOSE: 'CAJAS.CLOSE',
        VIEW: 'CAJAS.VIEW'
    },
    EMPLEADOS: {
        CREATE: 'EMPLEADOS.CREATE',
        READ: 'EMPLEADOS.READ',
        UPDATE: 'EMPLEADOS.UPDATE',
        DELETE: 'EMPLEADOS.DELETE'
    }
};

// Función helper para verificar permisos (opcional)
const hasPermission = (userPermisos, requiredPermission) => {
    const [section, action] = requiredPermission.split('.');
    return userPermisos?.[section]?.[action] === true;
};

module.exports = PRIVILEGES;